name: Repository dispatch receive

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      sha256:
        required: true
        type: string

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: print version
        run: echo ${{ inputs.version }}
      - name: print sha256
        run: echo ${{ inputs.sha256 }}
