name: Repository dispatch receive

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      sha256:
        required: true
        type: string

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: print version
        run: echo ${{ inputs.version }}
      - name: print sha256
        run: echo ${{ inputs.sha256 }}

  create-pullrequest:
    runs-on: ubuntu-latest
    steps:
      - name: setup git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - uses: actions/checkout@v4
      - run: git switch -c test
      - name: before file
        run: cat src/index.ts
      - run: sed -i 's/yellow/red/g' src/index.ts
      - name: after file
        run: cat src/index.ts
      - run: |
          git add .
          git commit --message 'file changed'
          git push origin test
      - run: |
          gh pr create \
            --title "[Test] Create Pull Request From GitHub Actions" \
            --body "GitHub Actions created." \
            --label "test" > pr-url.txt
      - name: print pr url
        run: cat pr-url.txt
      - run: gh pr merge $(cat pr-url.txt) --squash
    env:
      GH_TOKEN: ${{ github.token }}
